version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "daily" }
    open-pull-requests-limit: 10
    labels: ["deps"]
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

