name: Markdown Links
on:
  pull_request:
  schedule: [{cron: "0 2 * * 1"}]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: "yes"
          config-file: ".github/mlc-config.json"
